idf_component_register(
    SRCS
        "main.c"
        "crypto.c"
        "integrity_checker.c"
        "logger.c"
        "rollback.c"
        "serial_comm.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        mbedtls
        nvs_flash
        driver
        spi_flash
        esp_partition
 app_update
)